### ISSUE TITLE
White icons on white background on Fedora 32

### ISSUE THREAD

**Issue by YaLTeR** [flathub/org.kde.kdenlive#55] opened 2020-05-08 08:14 UTC
Kdenlive installed from Flathub on a fresh Fedora 32 installation:
![изображение](https://user-images.githubusercontent.com/1794388/81386014-fd1efe00-911c-11ea-82dd-80b8b63b2ed3.png)

**Comment by eszlari** [comment] 2020-05-23 16:23
duplicate of: https://github.com/flathub/org.kde.kdenlive/issues/53

**Closed by eszlari** 2020-05-23 16:23 UTC
