### ISSUE TITLE
Can't open a file

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.kde.kdenlive#1] opened 2018-01-05 16:02 UTC
When trying to use File -> Open on Endless OS 3.3.8 I get:

> trying to load "/usr/lib/plugins/kf5/kio/file.so" from "/usr/lib/plugins/kf5/kio/file.so"
> QXcbConnection: XCB error: 8 (BadMatch), sequence: 622, resource id: 94371863, major code: 155 (Unknown), minor code: 11

**Comment by eszlari** [comment] 2018-01-05 16:13
https://github.com/flatpak/flatpak/issues/1276
https://bugs.kde.org/show_bug.cgi?id=388234

Might be related to, because it worked before:
https://github.com/KDE/flatpak-kde-runtime/commit/d17671207dfb71cce86abf641df34f5edc7dbd2e

Maybe @aleixpol or @grulja have an idea.

**Comment by eszlari** [comment] 2018-01-08 04:27
I think, I found the cause, see:
https://github.com/flatpak/flatpak/issues/1276#issuecomment-355882326

**Comment by eszlari** [comment] 2018-01-15 14:59
This fixed now.

**Closed by eszlari** 2018-01-15 14:59 UTC
