### ISSUE TITLE
Audio devices not available

### ISSUE THREAD

**Issue by nigelsim** [flathub/org.kde.kdenlive#367] opened 2024-04-17 04:13 UTC
Using Kdenlive 24.02.1 under Ubuntu 22.04.4 I can not record audio for voice overs. The device list is empty. Other flatpak audio apps like OBS and Ardure 8 work fine.

![Screenshot from 2024-04-17 14-09-10](https://github.com/flathub/org.kde.kdenlive/assets/2869/4c7ee246-fcab-4df6-9364-5afbfec1fb89)

I'm running Pipewire, which is providing both JACK and Pulseaudio devices.

Console output:

```
Qt: Session management error: Could not open network socket
kf.config.core: Watching absolute paths is not supported "/usr/share/color-schemes/BreezeDark.colors"
profilePath from KdenliveSetting::mltPath:  "/app/share/mlt-7/profiles"
meltPath from KdenliveSetting::meltPath:  "/app/bin/melt"
plugin not available: "region"
Empty metadata for  "telecide"
plugin not available: "avfilter.acompressor"
plugin not available: "avfilter.aecho"
plugin not available: "avfilter.agate"
plugin not available: "avfilter.atadenoise"
plugin not available: "avfilter.bs2b"
plugin not available: "avfilter.bwdif"
plugin not available: "avfilter.deblock"
plugin not available: "avfilter.dedot"
plugin not available: "avfilter.deflate"
plugin not available: "avfilter.derain"
plugin not available: "avfilter.doubleweave"
plugin not available: "avfilter.field"
plugin not available: "avfilter.framestep"
plugin not available: "avfilter.fspp"
plugin not available: "avfilter.graphmonitor"
plugin not available: "avfilter.hqdn3d"
plugin not available: "avfilter.inflate"
plugin not available: "avfilter.lagfun"
plugin not available: "avfilter.loudnorm"
plugin not available: "avfilter.random"
plugin not available: "avfilter.removegrain"
plugin not available: "avfilter.separatefields"
plugin not available: "avfilter.shuffleplanes"
plugin not available: "avfilter.sofalizer"
plugin not available: "avfilter.sr"
plugin not available: "avfilter.tmix"
plugin not available: "avfilter.w3fdif"
plugin not available: "avfilter.weave"
plugin not available: "avfilter.yadif"
plugin not available: "frei0r.baltan"
plugin not available: "frei0r.bgsubtract0r"
plugin not available: "frei0r.delay0r"
plugin not available: "frei0r.delaygrab"
plugin not available: "frei0r.facebl0r"
plugin not available: "frei0r.facedetect"
plugin not available: "frei0r.lightgraffiti"
plugin not available: "frei0r.lightgraffiti"
plugin not available: "frei0r.tehRoxx0r"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "movit.blur"
plugin not available: "movit.sharpen"
plugin not available: "movit.diffusion"
plugin not available: "movit.flip"
plugin not available: "movit.glow"
plugin not available: "movit.lift_gamma_gain"
plugin not available: "movit.mirror"
plugin not available: "movit.opacity"
plugin not available: "movit.rect"
plugin not available: "movit.saturation"
plugin not available: "movit.unsharp_mask"
plugin not available: "movit.vignette"
plugin not available: "movit.white_balance"
plugin not available: "timewarp"
=== /// CANNOT ACCESS SPEECH DICTIONARIES FOLDER
qt.qml.typeresolution.cycle: Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
qt.qml.typeresolution.cycle: Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
begin
OpenGL vendor "Intel"
OpenGL renderer "Mesa Intel(R) UHD Graphics 620 (KBL GT2)"
OpenGL threaded? true
OpenGL ES? false
OpenGL maximum texture size = 16384
OpenGL maximum viewport size = 16384 x 16384
end
begin
OpenGL vendor "Intel"
OpenGL renderer "Mesa Intel(R) UHD Graphics 620 (KBL GT2)"
OpenGL threaded? true
OpenGL ES? false
OpenGL maximum texture size = 16384
OpenGL maximum viewport size = 16384 x 16384
end
:::: NOT FOUND DOCUMENT GUIDES !!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!
qt.qml.typeresolution.cycle: Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
qrc:/qml/timeline.qml:509: ReferenceError: proxy is not defined
qrc:/qml/timeline.qml:489: ReferenceError: proxy is not defined
==== NO PREVIOUS TIMELINE
::::::::::: connecting timeline:  QUuid("{dadc5e61-6ae4-45d7-a5b2-8497ece61bb7}") , DUR:  0
root context get sub model new function
HHHHHHHHHHHH
INVALID BIN PLAYLIST...
=== OPENING FILE WITH TRACKS:  5
:::: FOUND TRACTOR WITH TRACKS:  2 

___________________________
=== MODEL DATA CHANGED: MUTE DONE TRACK NOT FOUND!!!
:::: FOUND TRACTOR WITH TRACKS:  2 

___________________________
=== MODEL DATA CHANGED: MUTE DONE TRACK NOT FOUND!!!
:::: FOUND TRACTOR WITH TRACKS:  2 

___________________________
=== MODEL DATA CHANGED: MUTE DONE TRACK NOT FOUND!!!
:::: FOUND TRACTOR WITH TRACKS:  2 

___________________________
=== MODEL DATA CHANGED: MUTE DONE TRACK NOT FOUND!!!
===== ACTIVATING DOCUMENT:  QUuid("{dadc5e61-6ae4-45d7-a5b2-8497ece61bb7}") 
::::::::::::::::::::::
detected format: Motion-JPEG: MJPG
Size: 1280x720: 1/30, 
Size: 960x540: 1/30, 
Size: 848x480: 1/30, 
Size: 640x480: 1/30, 
Size: 640x360: 1/30, 
detected format: YUYV 4:2:2: YUYV
Size: 1280x720: 1/10, 
Size: 640x480: 1/30, 
Size: 640x360: 1/30, 
Size: 424x240: 1/30, 
Size: 320x240: 1/30, 
Size: 320x180: 1/30, 
Size: 160x120: 1/30, 
::::: CHECKING PYTHON, RQST VENV:  false
=== /// CANNOT ACCESS SPEECH DICTIONARIES FOLDER
::::: CHECKING PYTHON, RQST VENV:  false
::::: CHECKING PYTHON, RQST VENV:  false
::: RUNNONG SCRIPT:  "/usr/bin/python3"  =  QList("/app/share/kdenlive/scripts/checkpackages.py", "--check", "srt", "vosk")
::: RUNNONG SCRIPT:  "/usr/bin/python3"  =  QList("/app/share/kdenlive/scripts/checkpackages.py", "--check", "openai-whisper", "srt", "torch")
==== NO PREVIOUS TIMELINE
==== ABORTING NO TIMELINE AVAILABLE
::: REQUESTING SELECTION CLEAR!!!!!!
::::::==

CLOSING TIMELINE MODEL

::::::::
... FOUND CLIP:  "2"  =  "Sequences"
========== READY FOR TASK DISCARD ON:  3
begin
begin
QPaintDevice: Cannot destroy paint device that is being painted

```

**Comment by wlmqljj** [comment] 2024-04-21 04:00
I encounter same problem on manjaro with distro-built package.  :(
I do not really understand "audio plugin" is for what. 
PulseAudio? Gstreamer? 
Mine is pipewire.

**Comment by travier** [comment] 2024-04-21 11:29
This should probably be reported upstream then.

**Comment by wlmqljj** [comment] 2024-04-23 11:25
Caused by not being implemented for qt6. Upstream is fixed now.
CI build works for me.
give CI a try ;)
https://cdn.kde.org/ci-builds/multimedia/kdenlive/master/

Fixed by: https://invent.kde.org/multimedia/kdenlive/-/merge_requests/494

**Comment by travier** [comment] 2024-04-23 12:37
Thanks, I've pushed this patch to https://github.com/flathub/org.kde.kdenlive/pull/366. Please help us test it.

**Comment by travier** [comment] 2024-04-29 22:23
Please test https://github.com/flathub/org.kde.kdenlive/pull/366

**Comment by nigelsim** [comment] 2024-04-30 01:00
Thanks @travier this appears to work. I can see the device and the UV metre shows input. I'll test more later

**Comment by nigelsim** [comment] 2024-04-30 01:37
Hi, it works correctly now. Thanks

**Closed** 2024-04-30 11:05 UTC
