### ISSUE TITLE
Render not working properly since pull request 42442e91b668dd75c05b3fc202d9d6dc18dbd7af9cf1227535ae26b10bb89072

### ISSUE THREAD

**Issue by jakubklos77** [flathub/org.kde.kdenlive#335] opened 2024-02-05 13:44 UTC
As explained in the pull request
https://github.com/flathub/org.kde.kdenlive/pull/329#issuecomment-1926335085

rendering does not work properly since the pull request
42442e91b668dd75c05b3fc202d9d6dc18dbd7af9cf1227535ae26b10bb89072

1. It shows "INVALID" for any title clip
2. It does not render effects (fade in)
It seems the render is much faster than before which is suspicious.

If I revert on flatpak to the previous version it all works.

I assume this is this very pull request which does not work:
```
    Commit: 42442e91b668dd75c05b3fc202d9d6dc18dbd7af9cf1227535ae26b10bb89072
   Subject: Add AppStream metadata patch (ca976c86)
      Date: 2024-02-02 21:40:04 +0000
```

And this is the previous one which works properly:
```
    Commit: 82dab8d18d7706a9197d301acf21da9cbaafe82a36fa3512dc931028386467b8
   Subject: Update r57.tar.gz to 58 (25e3eab9)
      Date: 2024-01-25 23:29:58 +0000
```

Reproduction:
Place any video and add a 1sec fade in effect. Render. The video will not have any effect.

**Comment by travier** [comment] 2024-02-05 15:08
Potential temporary workaround in https://github.com/flathub/org.kde.kdenlive/pull/334

**Comment by travier** [comment] 2024-02-05 15:23
https://github.com/flathub/org.kde.kdenlive/pull/329#issuecomment-1927053823 > If https://github.com/flathub/org.kde.kdenlive/pull/334 does not solve this issue then it's likely that the issue is elsewhere.

**Comment by jakubklos77** [comment] 2024-02-20 07:30
Yeah, I haven't tested the recent updates but I wonder if it fails for all users or just us. If you notice the rendering is so much faster on these builds where the issue exist. So either some hw acceleration has been added or something else...

**Comment by jakubklos77** [comment] 2024-02-21 08:07
Yup, still happening, just tried it again with a new project

**Comment by j-b-m** [comment] 2024-02-21 08:26
So starting the app with:
`flatpak run --socket=x11 org.kde.kdenlive`
should fix the bug if my guess is correct

**Comment by jakubklos77** [comment] 2024-02-21 09:05
Unfortunately, this is not working either. Have just tested it. Must be something else

**Comment by j-b-m** [comment] 2024-02-21 12:36
It's my command line that was incorrect, but the problem definitely is related to using wayland. With this command line the bug goes away, this was the correct way to disable wayland and switch to xcb:
`flatpak run --nosocket=wayland org.kde.kdenlive`

**Comment by jakubklos77** [comment] 2024-02-21 13:32
Great, thank you.  You are right, after disabling wayland, it really works. I wonder how a display server can affect the actual  video rendering... Thanks again

**Comment by j-b-m** [comment] 2024-02-24 06:32
I am not familiar enough with Flatpak to propose a fix... The Appimage enforces X11 but for different reasons.
Kdenlive's rendering happens through a small helper app `kdenlive_render`, which needs access to graphical resources in Qt. Maybe something needs to be done in the manifest to allow that...

**Comment by travier** [comment] 2024-02-24 14:39
Could you file a bug upstream in bugs.kde.org? Thanks

**Comment by travier** [comment] 2024-02-24 14:42
New test build in https://github.com/flathub/org.kde.kdenlive/pull/334

**Comment by j-b-m** [comment] 2024-02-27 05:15
So I am progressing on this. MLT (Kdenlive's video engine) expects a `DISPLAY` environment variable to be set on runtime:
https://github.com/mltframework/mlt/blob/master/src/modules/qt/common.cpp#L39
When running Kdenlive's Flatpak on X11, the `DISPLAY` variable is correctly set.
However, when running on Wayland, `DISPLAY` is empty, but `WAYLAND_DISPLAY` is set to "wayland-0".
So I guess the `DISPLAY` environment is not a reliable test in Wayland, and MLT should be patched to also check for `WAYLAND_DISPLAY` before aborting.

**Comment by jakubklos77** [comment] 2024-02-27 07:40
Good find, in my Ubuntu 22.04 env must DISPLAY environment var is set to the usual :0.
```
WAYLAND_DISPLAY=wayland-0
GNOME_SETUP_DISPLAY=:1
DISPLAY=:0
```
Not sure if it helps. But you are right, the MLT should consider the WAYLAND_DISPLAY var as well and with a higher priority than the DISPLAY one
Thank you

**Comment by j-b-m** [comment] 2024-02-28 05:24
A fix has now been pushed to MLT's git master, and will be released with MLT 7.24.0. 
Wayland can be re-enabled for Kdenlive if we update MLT's reference commit to `025afafa8e7bbafebd32651b6895ee68ec1c825b`

**Comment by travier** [comment] 2024-02-29 17:19
@jlskuz Do you think this is reasonable or should we stay with https://github.com/flathub/org.kde.kdenlive/pull/334 and update MLT later?

**Closed** 2024-02-29 19:40 UTC

**Comment by travier** [comment] 2024-03-08 15:04
Hey folks, Can you try the build from https://github.com/flathub/org.kde.kdenlive/pull/347 and report success / failure? Thanks
